"""Lifecycle helpers for downloadable files generated by tools.

The ``create_pptx`` / ``create_document`` / ``create_mindmap`` tools render
real Office / PDF / SVG files into ``.generated/{id}.{ext}`` and hand back a
``downloadUrl``. This module owns
the format-agnostic plumbing shared by every generator: persisting a file under a
random id, resolving a download id back to a path (without path traversal),
cleaning up expired files, copying one into the user's Downloads folder, and
mapping an extension to its MIME type. ``presentations``, ``documents``, and
``mindmaps`` build their format-specific content on top of
:func:`store_generated_file`.
"""

from __future__ import annotations

import re
import secrets
import shutil
import time
from pathlib import Path
from typing import Any, Callable

from deepseek_infra.core.config import GENERATED_DIR
from deepseek_infra.core.errors import AppError, ErrorCode

GENERATED_FILE_MAX_AGE_SECONDS = 6 * 3600  # 生成文件保留 6 小时后清理

# 支持的可下载文件类型：扩展名 -> MIME。新增一种生成器只要在这里登记扩展名即可，
# resolve / cleanup / 下载响应都会自动覆盖到。
GENERATED_MEDIA_TYPES: dict[str, str] = {
    "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "pdf": "application/pdf",
    "md": "text/markdown; charset=utf-8",
    "svg": "image/svg+xml",
}

_ID_RE = re.compile(r"[0-9a-f]{32}")
_DOC_EXT_RE = re.compile(r"\.(?:pptx|docx|pdf|md|svg)$", flags=re.IGNORECASE)


def _safe_filename(title: str) -> str:
    name = re.sub(r"[^\w一-鿿 -]", "", str(title or "")).strip()
    return name[:60] or "document"


def download_url(file_id: str) -> str:
    return f"/api/download?id={file_id}"


def store_generated_file(title: str, ext: str, writer: Callable[[Path], None]) -> dict[str, Any]:
    """把生成的文件落盘到 ``.generated/{id}.{ext}``，返回 fileId/filename/downloadUrl。

    ``writer`` 收到目标路径并负责把内容写进去（例如 ``prs.save`` 或 ``doc.save``）。
    每次落盘前顺手清理过期文件，避免目录无限增长。
    """
    normalized_ext = str(ext or "").strip().lower().lstrip(".")
    if normalized_ext not in GENERATED_MEDIA_TYPES:
        raise AppError(f"不支持的生成文件类型：{ext}", code=ErrorCode.INVALID_PAYLOAD)
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    cleanup_generated_files()
    file_id = secrets.token_hex(16)
    writer(GENERATED_DIR / f"{file_id}.{normalized_ext}")
    return {
        "fileId": file_id,
        "filename": f"{_safe_filename(title)}.{normalized_ext}",
        "downloadUrl": download_url(file_id),
    }


def cleanup_generated_files() -> None:
    """删除过期的生成文件。任何 IO 异常都静默吞掉，不影响主流程。"""
    try:
        if not GENERATED_DIR.exists():
            return
        now = time.time()
        for ext in GENERATED_MEDIA_TYPES:
            for path in GENERATED_DIR.glob(f"*.{ext}"):
                try:
                    if now - path.stat().st_mtime > GENERATED_FILE_MAX_AGE_SECONDS:
                        path.unlink(missing_ok=True)
                except OSError:
                    continue
    except OSError:
        pass


def resolve_generated_file(file_id: str) -> Path | None:
    """把下载请求的 id 解析成磁盘路径；只接受 32 位十六进制 id，杜绝路径遍历。

    一个 id 在磁盘上只会对应一种扩展名，按已登记类型逐一探测即可。
    """
    if not _ID_RE.fullmatch(str(file_id or "")):
        return None
    for ext in GENERATED_MEDIA_TYPES:
        path = GENERATED_DIR / f"{file_id}.{ext}"
        if path.is_file():
            return path
    return None


def download_descriptor(path: Path) -> tuple[str, str]:
    """给下载响应返回 (MIME, 附件文件名)。文件名按类型给个通用名，扩展名取自实际文件。"""
    ext = path.suffix.lower().lstrip(".")
    media_type = GENERATED_MEDIA_TYPES.get(ext, "application/octet-stream")
    base = "presentation" if ext == "pptx" else "mindmap" if ext == "svg" else "notes" if ext == "md" else "document"
    return media_type, f"{base}.{ext}"


def save_generated_file_to_downloads(file_id: str, filename: str = "", *, downloads_dir: Path | None = None) -> dict[str, Any]:
    source = resolve_generated_file(file_id)
    if source is None:
        raise AppError("文件不存在或已过期", code=ErrorCode.NOT_FOUND, status=404)

    ext = source.suffix.lower().lstrip(".")
    target_dir = downloads_dir or _downloads_dir()
    target_dir.mkdir(parents=True, exist_ok=True)
    target = _unique_download_path(target_dir, _download_filename(filename, ext))
    shutil.copy2(source, target)
    return {"ok": True, "filename": target.name, "path": str(target), "downloadUrl": download_url(file_id)}


def _downloads_dir() -> Path:
    home = Path.home()
    return home / "Downloads"


def _download_filename(value: str, ext: str) -> str:
    """扩展名以磁盘上真实文件为准，前端传来的名字只取它的基名部分。"""
    raw = str(value or "").strip()
    raw = _DOC_EXT_RE.sub("", raw)
    raw = re.sub(r"^(?:点击)?下载\s*", "", raw, flags=re.IGNORECASE).strip()
    base = _safe_filename(raw) or ("presentation" if ext == "pptx" else "mindmap" if ext == "svg" else "notes" if ext == "md" else "document")
    return f"{base}.{ext}"


def _unique_download_path(directory: Path, filename: str) -> Path:
    base = Path(filename).stem or "document"
    suffix = Path(filename).suffix or ".bin"
    candidate = directory / f"{base}{suffix}"
    index = 2
    while candidate.exists():
        candidate = directory / f"{base} ({index}){suffix}"
        index += 1
    return candidate
